name: CI

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  # CI workflow isn't triggered by release-please PRs: https://github.com/google-github-actions/release-please-action#github-credentials
  # Instead of using a PAT, trigger CI workflows on the mandatory review of release PRs
  pull_request_review:
    types: [submitted]
    branches:
      - 'release-please*'

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    name: Node ${{ matrix.node }} CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Update npm
        run: npm install -g npm@9.6.6

      - name: Install dependencies
        run: npm ci

      - name: Check format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test

      - name: Build module
        run: npm run build
